Improve performance/lineage excel generation
usafsam/mad_river_wf pull request #12
Opened 2022-02-18 03:45 UTC by fanninpm

- Remove SampleSheet.csv from lineage excel
- Split PERFORMANCE_LINEAGE_EXCEL process
- Always generate a lineage excel file

2022-02-26 03:52 UTC, friesac requested changes

2022-02-26 03:52 UTC, friesac commented on bin/performance_lineage_excel.py
> -
Perhaps I'm misinterpreting, but when has the sample sheet been a output sheet in the lineage excel? I thought it's always been just the pangolin and nextclade output summary?

2022-02-26 03:52 UTC, friesac commented on bin/performance_lineage_excel.py
This is minor, but could we sort each worksheet descending on the sample name.

2022-02-26 04:07 UTC, fanninpm commented on bin/performance_lineage_excel.py
> -
This was used when `ivar consensus` spit out overly long FASTA headers (prior to #4) to shorten the sample names.

2022-02-26 04:16 UTC, friesac commented on bin/performance_lineage_excel.py
> -
Ah, right, thanks.

2022-03-01 17:51 UTC, fanninpm commented on bin/performance_lineage_excel.py
I identified why those files aren't being sorted properly. In `main.nf`, when constructing `ch_combined_consensus_fasta`, I should probably use something like `sort: { it.getSimpleName() }` instead of `sort: true`.

2022-03-02 02:38 UTC, friesac approved these changes

2022-03-02 02:46 UTC, fanninpm commented on bin/performance_lineage_excel.py
See #17 for a potential fix.

2022-03-04 02:43 UTC, merged